ドロワーを追加
pyconjp/pycon.jp.2019 pull request #16
Opened 2019-07-26 13:46 UTC by sudame

## Summary

Navigation Drawerの追加

## Done

- Navigation Drawerの追加

## ScreenShots

| ![Screen Shot 2019-07-26 at 18 13 07](https://user-images.githubusercontent.com/6907421/61955836-d6ad2d80-aff6-11e9-8f0a-a18924e58e30.png) | ![Screen Shot 2019-07-26 at 18 13 13](https://user-images.githubusercontent.com/6907421/61955857-e167c280-aff6-11e9-8252-3e7a94c860ff.png) |
|:-:|:-:|
| 閉じている状態 | 開いている状態 |

## Next

- コンテンツが増えたら項目追加
- ネストされたリストへの対応
- 直書きではなくデータとしてメニューを持たせればより冗長性が無くなる

2019-07-30 01:41 UTC, ikedaosushi requested changes

2019-07-30 01:41 UTC, ikedaosushi commented on components/partials/Header.vue
> +import { mapState, mapActions, mapMutations } from 'vuex';
`mapMutations` 使ってますか？

2019-07-30 01:41 UTC, ikedaosushi commented on components/partials/Header.vue
> +                v-icon(medium v-if="$store.state.drawerIsOpen") close
`mapState` 使ってほしいです！

2019-07-30 01:41 UTC, ikedaosushi commented on components/partials/Header.vue
> +            this.$store.commit('toggleDrawer');
`mapActions` 使って欲しいです！

2019-07-30 01:41 UTC, ikedaosushi commented on components/partials/NavigationDrawer.vue
> +        a(href="https://pyconjp.blogspot.com/2019/06/pyconjp-2019-tickets.html" target="_blank" rel="noreferrer noopener" @click="$store.commit('toggleDrawer')")
`mapActions` 使ってほしいです！

2019-07-30 01:41 UTC, ikedaosushi commented on components/partials/NavigationDrawer.vue
> +        return this.$store.state.drawerIsOpen
`mapState` 使ってほしいです！

2019-07-30 01:41 UTC, ikedaosushi commented on components/partials/NavigationDrawer.vue
> +        this.$store.commit('setDrawer', val)
`mapActions` 使ってほしいです！

2019-07-30 01:41 UTC, ikedaosushi commented on components/partials/NavigationDrawer.vue
> +.primary {
色はできれば `nuxt.config.js` に `primary` のように定義して使ってほしいです！

2019-07-30 11:56 UTC, sudame commented
## Updates
- map**を使うように変更しました
    - mapStateについてはmapActions, mapMutationsと同じように文字列引数を渡す形式にリファクタリングしました
- 不要なconsole.logを削除しました
- 不要な色定義を削除しました

2019-08-01 03:20 UTC, ikedaosushi commented
ありがとうございました！

2019-08-01 03:20 UTC, ikedaosushi commented
ありがとうございました！LGTMです

2019-08-01 03:37 UTC, merged